server:
  port: 8080

spring:
  main:
   allow-bean-definition-overriding: true

  datasource:
    username: root
    password: lmh123
    url: jdbc:mysql://8.130.31.247:3306/jizhang?autoReconnect=true&amp&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 8.130.31.247

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto