server:
  port: 8080

spring:
  datasource:
    username: root
    password: lmh123
    url: jdbc:mysql://mysql-server:3306/jizhang?autoReconnect=true&amp&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

  #邮箱服务
  mail:
    host: smtp.qq.com
    username: twentyue@qq.com
    password: ityfazccegdgdfji
    default-encoding: UTF-8
    from: ${spring.mail.username}
    protocol: smtp
  application:
    name: jizhang

  redis:
    host: redis

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto